version: "3.8"

services:
  app:
    # Anda juga bisa biarkan build: . untuk local, tapi saat di VPS kita mau pull image
    # build: .
    image: ghcr.io/ajisdzalparo/nika.id:latest
    container_name: nikaid-app
    restart: unless-stopped
    ports:
      - "3000:3000"
  postgres:
    image: postgres:16-alpine
    container_name: nikaid-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: nikaid
      POSTGRES_PASSWORD: nikaid_password
      POSTGRES_DB: nikaid
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nikaid"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
